apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
type: application
description: "A Helm chart for Kubernetes to install the 'Watson Speech to Text' runtime to Kubernetes."
name: "watson-stt-kubernetes"