apiVersion: v1
kind: Service
metadata:
  name: ibm-watson-stt-embed
  namespace: {{ .Values.default_namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "ibm-watson-stt-embed"
    app.kubernetes.io/component: "runtime"
    app.kubernetes.io/instance: "example"
  ports:
    - name: runtime
      protocol: TCP
      port: 1080
      targetPort: 1080