apiVersion: v1
kind: Service
metadata:
  name: watson-stt-container-vpc-nlb
#  namespace: {{ .Values.default_namespace }}
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: "ibm-watson-stt-embed"
    app.kubernetes.io/component: "runtime"
    app.kubernetes.io/instance: "example"
  ports:
   - name: http
     protocol: TCP
     port: 1080
     targetPort: 1080